application: jamtodaycdn
version: 0-01
runtime: python
api_version: 1

handlers:
- url: /assets
  static_dir: assets
  
- url: /bin
  static_dir: bin
    
- url: /i/(img|thumb).*
  script: frontend.py

- url: /.*
  script: backend.py
  login: admin
